import type { Metadata } from 'next'
import { Montserrat } from 'next/font/google'

//styles
import '@/scss/main.scss';

//redux
import ReduxProvider from '@/redux/provider';

//components
import CheckAuth from '@/components/ClientSide/CheckAuth';

const montserrat = Montserrat({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Social Network',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <ReduxProvider>
          {children}
          <CheckAuth />
        </ReduxProvider>
      </body>
    </html>
  )
}
